name: Tests
on: [push]

jobs:
  # Runtime Tests
  runtime-test:
    name: Runtime Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.536'

      - name: Cache maven
        uses: actions/cache@v2
        env:
          cache-name: cache-maven
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cache gitlibs
        uses: actions/cache@v2
        env:
          cache-name: cache-gitlibs
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cache JSC
        uses: actions/cache@v2
        env:
          cache-name: cache-jsc
        with:
          path: WebKit
          key: ${{ runner.os }}-jsc
          restore-keys: |
            ${{ runner.os }}-jsc

      - name: Build tests
        run: clojure -A:runtime.test.build

      - name: Install JSC
        run: ./ci/install_jsc.sh

      - name: Run tests
        run: WebKit/WebKitBuild/Release/bin/jsc builds/out-adv/core-advanced-test.js

  # Self-host Tests
  self-host-test:
    name: Self-host Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.536'

      - name: Cache maven
        uses: actions/cache@v2
        env:
          cache-name: cache-maven
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cache gitlibs
        uses: actions/cache@v2
        env:
          cache-name: cache-gitlibs
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Build tests
        run: clojure -A:selfhost.test.build

      - name: Run tests
        run: node builds/out-self/core-self-test.js

  # Compiler Tests
  compiler-test:
    name: Compiler Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.536'

      - name: Cache maven
        uses: actions/cache@v2
        env:
          cache-name: cache-maven
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cache gitlibs
        uses: actions/cache@v2
        env:
          cache-name: cache-gitlibs
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Run tests
        run: clojure -A:compiler.test:compiler.test.run

  # CLI Tests
  cli-test:
    name: CLI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.536'

      - name: Cache maven
        uses: actions/cache@v2
        env:
          cache-name: cache-maven
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cache gitlibs
        uses: actions/cache@v2
        env:
          cache-name: cache-gitlibs
        with:
          path: ~/.gitlibs
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Build Uberjar
      - run: ./script/uberjar

      - name: Run tests
        run: clojure -A:cli.test.run
